### ISSUE TITLE
bbdc-newword-export script CORS problem

### ISSUE THREAD

**Issue by boa-z** [shiquda/shiquda_UserScript#5]
encounter following error when running [bbdc-newword-export.js](https://github.com/shiquda/shiquda_UserScript/blob/main/%E4%B8%8D%E8%83%8C%E5%8D%95%E8%AF%8D/bbdc-newword-export.js)

```text
Access to XMLHttpRequest at 'https://www.bbdc.cn/api/user-new-word?page=0' from origin 'https://bbdc.cn' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by shiquda** [comment]
Hi there, I cannot reproduce the same error you mentioned.
